version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: 'mysql'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  composer:
    image: composer
    container_name: 'composer'

  web:
    container_name: 'web'
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - composer

volumes:
  db_data:
