version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: 'mysql'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web:
    container_name: 'web'
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
      - "8080:80"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html/src
    depends_on:
      - mysql

volumes:
  db_data:
